### ISSUE TITLE
'Thin slices' exercise needs explanation

### ISSUE THREAD

**Issue by gcapes** [gruel/python-novice-inflammation#9]
This exercise doesn't give any explanation for the solutions. Also, it seems that the first answer is simply an empty 0 * 0 array `[ ]`, but the second answer is a 0 * 40 empty array. Is this the same as a 0 * 0 empty array(?)
`(data[3:3,:]).shape` gives `(0, 40)`

**Comment by gruel** [comment]
What do you think about that explanation? I am not sure that it is clear... It is for me but for a novice....

"Both commands will produce an empty array but if we are looking at the shape of the array, we can notice that for the second answer the shape was converted to (0,40) which can be confusing since we would have expected a shape to be null but we have to remember that a shape is not real in term of computing. It is only an attribute affected to our object. The space in memory use by that object will 0x40 which is 0. Numpy could have changed the second value but it would have add unnecessarily overhead."

**Comment by gcapes** [comment]
Yep, it's pretty clear. I've just reworded a little bit for clarity -- I hope it retains the original meaning:

Both commands will produce an empty array but if we look at the shape of the arrays, the second answer gives a shape of (0,40). This can be confusing since we would have expected a shape to be null but we have to remember that a shape is not real in term of computing. It is only an attribute attributed to our object. The space in memory used by that object will be 0x40 which is 0. Numpy could have changed the second shape value to 0, but it would have add unnecessarily overhead.

**Comment by gruel** [comment]
Thanks.
